"""nix-dag-ftps-simple-transfer — upload a file from shared storage to the FTPS server."""

import ftplib
import logging
import ssl
from datetime import datetime, timedelta
from functools import cached_property

from airflow import DAG
from airflow.providers.ftp.hooks.ftp import FTPSHook
from airflow.providers.ftp.operators.ftp import FTPSFileTransmitOperator
from airflow.providers.standard.operators.python import PythonOperator

DAG_DOC_MD = """
### nix-dag-ftps-simple-transfer

Uploads a file from shared storage to the **g1pro FTPS server**, then verifies
it landed.

#### Trigger

Manual only (`schedule=None`). Optional run conf:

```json
{"filename": "probe.txt"}
```

Defaults to `probe.txt`.

#### Flow

| Task | Does |
|---|---|
| `upload_file` | `FTPSFileTransmitOperator` puts the file into `/upload/` |
| `verify_upload` | re-connects, checks size and mtime on the server |

#### Source and destination

| | Path | Notes |
|---|---|---|
| Source | `/opt/airflow/dags/files/<filename>` | hostPath mount, same file in every pod |
| Destination | `/upload/<filename>` | inside the FTPS chroot |

The source lives on the server at `/mnt/external-storage/airflow-dags/files/`
and is mounted into every Airflow pod. It is **not** generated by the DAG:
under KubernetesExecutor each task gets a fresh pod, so a file written to local
disk by one task does not exist for the next.

The destination is the `ftpuser` chroot (`/mnt/external-storage/ftp` on disk).
Only `/upload` is writable — the chroot root is mode `555` and
`allow_writeable_chroot=NO`, so a `STOR` to `/` returns `553`.

To change the payload, edit the source file on the server:

```bash
ssh nickmsft@nixhome-linux-g1pro \\
  "vi /mnt/external-storage/airflow-dags/files/probe.txt"
```

#### Why a custom hook

The server presents a **self-signed certificate**. Stock `FTPSHook.get_conn()`
hardcodes `ssl.create_default_context()` with no way to supply a CA, so it
fails with `CERTIFICATE_VERIFY_FAILED`.

`MyFTPSHook` overrides `get_conn()` to build the context from the
`ftps_ca_cert` Variable — **certificate verification stays ON**, the CA is
trusted rather than bypassed. It also calls `prot_p()`, which the stock hook
omits; without it the uploaded bytes cross the network in plaintext.

The operator itself is the provider's own `FTPSFileTransmitOperator`; only its
`hook` property is overridden.

#### Requires

| Kind | Name | Purpose |
|---|---|---|
| Connection | `ftps_test_001` | host, login, password, port (conn type `FTP`) |
| Variable | `ftps_ca_cert` | PEM of `/etc/ssl/private/vsftpd.pem` |
| File | `files/<filename>` under the DAG folder | the payload to upload |
"""

FTPS_CONN_ID = "ftps_test_001"

# vsftpd chroots ftpuser; the chroot root is read-only (mode 555) and only
# /upload is writable. See g1pro.md §3.
REMOTE_DIR = "/upload"

# hostPath mount — /mnt/external-storage/airflow-dags on the host is
# /opt/airflow/dags in every pod, so the source file is visible to any worker.
LOCAL_DIR = "/opt/airflow/dags/files"

_FILENAME = "{{ dag_run.conf.get('filename', 'probe.txt') }}"
LOCAL_PATH = f"{LOCAL_DIR}/{_FILENAME}"
REMOTE_PATH = f"{REMOTE_DIR}/{_FILENAME}"


class MyFTPSHook(FTPSHook):
    """FTPSHook that trusts the g1pro self-signed CA and encrypts data transfers."""

    def get_conn(self) -> ftplib.FTP:
        from airflow.sdk import Variable

        if self.conn is not None:
            return self.conn

        # Host, login, password, port and passive flag all come from the
        # Airflow Connection (ftps_test_001) — same as the stock hook. Only
        # the TLS context differs, and it is the reason for this override.
        params = self.get_connection(self.ftp_conn_id)

        context = ssl.create_default_context(cadata=Variable.get("ftps_ca_cert"))

        if params.port:
            ftplib.FTP_TLS.port = params.port

        conn = ftplib.FTP_TLS(params.host, params.login, params.password, context=context)
        conn.prot_p()  # stock FTPSHook omits this — without it data is plaintext
        conn.set_pasv(params.extra_dejson.get("passive", True))

        self.conn = conn
        return self.conn


class MyFTPSFileTransmitOperator(FTPSFileTransmitOperator):
    """Official FTPS transfer operator, pointed at the CA-trusting hook."""

    @cached_property
    def hook(self) -> FTPSHook:
        return MyFTPSHook(ftp_conn_id=self.ftp_conn_id)


def verify_upload(**context):
    """Read back size and mtime from the server to prove the transfer landed."""
    task_log = logging.getLogger("airflow.task")

    filename = (context["dag_run"].conf or {}).get("filename", "probe.txt")
    remote_path = f"{REMOTE_DIR}/{filename}"

    with MyFTPSHook(ftp_conn_id=FTPS_CONN_ID) as hook:
        size = hook.get_size(remote_path)
        mod_time = hook.get_mod_time(remote_path)

    if not size:
        raise ValueError(f"{remote_path} is empty on the server — upload did not land")

    task_log.info(
        "[ftps_transfer] verified %s — %s bytes, modified %s", remote_path, size, mod_time
    )
    return {"path": remote_path, "size": size, "mod_time": str(mod_time)}


with DAG(
    dag_id="nix-dag-ftps-simple-transfer",
    description="Upload a file from shared storage to the g1pro FTPS server",
    schedule=None,  # manual trigger only
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["demo", "ftps", "transfer"],
    default_args={"owner": "nix", "retries": 1, "retry_delay": timedelta(seconds=30)},
    doc_md=DAG_DOC_MD,
) as dag:
    upload = MyFTPSFileTransmitOperator(
        task_id="upload_file",
        ftp_conn_id=FTPS_CONN_ID,
        local_filepath=LOCAL_PATH,
        remote_filepath=REMOTE_PATH,
        operation="put",
        doc_md="""
Uploads `/opt/airflow/dags/files/<filename>` to `/upload/<filename>` over FTPS,
with TLS on both the control and data channels.

Uses the provider's own `FTPSFileTransmitOperator` — only its `hook` property is
overridden, to supply the CA-trusting hook. `local_filepath` and
`remote_filepath` are templated fields, rendered from the run conf.

`FileNotFoundError` here means the source file is missing from the DAG folder's
`files/` directory on the server.
""",
    )

    verify = PythonOperator(
        task_id="verify_upload",
        python_callable=verify_upload,
        doc_md="""
Re-connects and reads the file's size and mtime back from the server, so a
silent partial upload fails the run rather than passing unnoticed.
""",
    )

    upload >> verify
