"""nix-dag-ftps-simple-transfer — upload a file from shared storage to the FTPS server."""

import ftplib
import logging
import ssl
from datetime import datetime, timedelta
from functools import cached_property

from airflow import DAG
from airflow.providers.ftp.hooks.ftp import FTPSHook
from airflow.providers.ftp.operators.ftp import FTPSFileTransmitOperator
from airflow.providers.standard.operators.python import PythonOperator

DAG_DOC_MD = """
### nix-dag-ftps-simple-transfer

Uploads a file from the DAG folder to the **FTPS server**, then verifies
it landed.

#### Trigger

Manual only (`schedule=None`). Optional run conf:

```json
{"filename": "probe.txt"}
```

Defaults to `probe.txt`.

#### Flow

| Task | Does |
|---|---|
| `upload_file` | `FTPSFileTransmitOperator` puts the file into `/upload/` |
| `verify_upload` | re-connects, checks size and mtime on the server |

#### Source and destination

| | Path | Notes |
|---|---|---|
| Source | `<AIRFLOW_HOME>/dags/files/<filename>` | DAG folder, mounted into every pod |
| Destination | `/upload/<filename>` | inside the FTPS chroot |

The source lives in the DAG folder, which is mounted into every Airflow pod.
It is **not** generated by the DAG:
under KubernetesExecutor each task gets a fresh pod, so a file written to local
disk by one task does not exist for the next.

The destination is inside the FTPS user's chroot. Typically only a subdirectory
is writable — an FTPS server generally refuses to run with a writable chroot
root, so a `STOR` to `/` returns `553`.

To change the payload, edit `dags/files/probe.txt` and redeploy.

#### Why a custom hook

The server presents a **self-signed certificate**. Stock `FTPSHook.get_conn()`
hardcodes `ssl.create_default_context()` with no way to supply a CA, so it
fails with `CERTIFICATE_VERIFY_FAILED`.

`MyFTPSHook` overrides `get_conn()` to build the context from the
`ftps_ca_cert` Variable — **certificate verification stays ON**, the CA is
trusted rather than bypassed. It also calls `prot_p()`, which the stock hook
omits; without it the uploaded bytes cross the network in plaintext.

The operator itself is the provider's own `FTPSFileTransmitOperator`; only its
`hook` property is overridden.

#### Requires

| Kind | Name | Purpose |
|---|---|---|
| Connection | `ftps_test_001` | host, login, password, port (conn type `FTP`) |
| Variable | `ftps_ca_cert` | PEM of the FTPS server's CA certificate |
| File | `files/<filename>` under the DAG folder | the payload to upload |
"""

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #

FTPS_CONN_ID = "ftps_test_001"

# The FTPS user is chrooted and the chroot root is read-only; only /upload
# accepts writes.
REMOTE_DIR = "/upload"

# The DAG folder is mounted into every pod, so a file committed to dags/files/
# is readable by any worker at runtime.
LOCAL_DIR = "/opt/airflow/dags/files"

# Jinja rather than a Python value: both paths are templated operator fields,
# so the filename is resolved per run from that run's conf. The f-string only
# splices the literal directory around the still-unrendered expression.
_FILENAME = "{{ dag_run.conf.get('filename', 'probe.txt') }}"
LOCAL_PATH = f"{LOCAL_DIR}/{_FILENAME}"
REMOTE_PATH = f"{REMOTE_DIR}/{_FILENAME}"


# --------------------------------------------------------------------------- #
# Hook and operator overrides
# --------------------------------------------------------------------------- #


class MyFTPSHook(FTPSHook):
    """FTPSHook that trusts a private CA and encrypts data transfers."""

    def get_conn(self) -> ftplib.FTP:
        # Imported inside the method, not at module scope: the DAG file is
        # re-parsed every dag-processor cycle, and Variable.get() at import time
        # would be a DB round-trip on every one of them.
        from airflow.sdk import Variable

        # The base hook treats self.conn as its connection cache; honouring it
        # keeps one FTPS session per hook instance rather than one per call.
        if self.conn is not None:
            return self.conn

        # Host, login, password, port and passive flag all come from the
        # Airflow Connection (ftps_test_001) — same as the stock hook. Only
        # the TLS context differs, and it is the reason for this override.
        params = self.get_connection(self.ftp_conn_id)

        # cadata adds the private CA *in addition to* the system trust store;
        # it does not disable verification. check_hostname stays on, so the
        # certificate's CN/SAN must still match the connection's host.
        context = ssl.create_default_context(cadata=Variable.get("ftps_ca_cert"))

        # ftplib.FTP_TLS takes no port argument, so the port can only be set on
        # the class. This mutates global state — acceptable because each task
        # runs in its own pod, but it would leak across DAGs in one process.
        if params.port:
            ftplib.FTP_TLS.port = params.port

        conn = ftplib.FTP_TLS(params.host, params.login, params.password, context=context)
        conn.prot_p()  # stock FTPSHook omits this — without it data is plaintext
        conn.set_pasv(params.extra_dejson.get("passive", True))

        self.conn = conn
        return self.conn


class MyFTPSFileTransmitOperator(FTPSFileTransmitOperator):
    """Official FTPS transfer operator, pointed at the CA-trusting hook."""

    # cached_property, matching the base class: `hook` is declared that way
    # upstream, so a plain @property would still override correctly but would
    # rebuild the hook on every access. Same decorator keeps one session per
    # task instance.
    @cached_property
    def hook(self) -> FTPSHook:
        return MyFTPSHook(ftp_conn_id=self.ftp_conn_id)


# --------------------------------------------------------------------------- #
# Task callables
# --------------------------------------------------------------------------- #


def verify_upload(**context):
    """Read back size and mtime from the server to prove the transfer landed."""
    task_log = logging.getLogger("airflow.task")

    # Rebuilt from conf rather than reusing REMOTE_PATH: that constant is Jinja
    # and only operator fields get rendered — a callable sees the raw braces.
    # Keep the "probe.txt" default in sync with the one above.
    filename = (context["dag_run"].conf or {}).get("filename", "probe.txt")
    remote_path = f"{REMOTE_DIR}/{filename}"

    # A fresh connection: this task is a separate pod from the upload, so it
    # genuinely re-reads server state rather than trusting the operator's word.
    with MyFTPSHook(ftp_conn_id=FTPS_CONN_ID) as hook:
        size = hook.get_size(remote_path)
        mod_time = hook.get_mod_time(remote_path)

    # Catches both a zero-byte file and a None size (server reported nothing) —
    # either means the put did not land, so fail loudly instead of returning.
    if not size:
        raise ValueError(f"{remote_path} is empty on the server — upload did not land")

    task_log.info(
        "[ftps_transfer] verified %s — %s bytes, modified %s", remote_path, size, mod_time
    )
    return {"path": remote_path, "size": size, "mod_time": str(mod_time)}


# --------------------------------------------------------------------------- #
# DAG definition
# --------------------------------------------------------------------------- #

with DAG(
    dag_id="nix-dag-ftps-simple-transfer",
    description="Upload a file from the DAG folder to the FTPS server",
    schedule=None,  # manual trigger only
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["demo", "ftps", "transfer"],
    default_args={"owner": "nix", "retries": 1, "retry_delay": timedelta(seconds=30)},
    doc_md=DAG_DOC_MD,
) as dag:
    upload = MyFTPSFileTransmitOperator(
        task_id="upload_file",
        ftp_conn_id=FTPS_CONN_ID,
        local_filepath=LOCAL_PATH,
        remote_filepath=REMOTE_PATH,
        operation="put",
        doc_md="""
Uploads `/opt/airflow/dags/files/<filename>` to `/upload/<filename>` over FTPS,
with TLS on both the control and data channels.

Uses the provider's own `FTPSFileTransmitOperator` — only its `hook` property is
overridden, to supply the CA-trusting hook. `local_filepath` and
`remote_filepath` are templated fields, rendered from the run conf.

`FileNotFoundError` here means the source file is missing from the DAG folder's
`files/` directory.
""",
    )

    verify = PythonOperator(
        task_id="verify_upload",
        python_callable=verify_upload,
        doc_md="""
Re-connects and reads the file's size and mtime back from the server, so a
silent partial upload fails the run rather than passing unnoticed.
""",
    )

    # Verification must not run unless the upload reported success.
    upload >> verify
